name: audioplayers_platform_interface
description: A common platform interface for the audioplayers plugin.
homepage: https://github.com/nmfisher/audioplayers/audioplayers_platform_interface
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5
  plugin_platform_interface: ^1.0.1
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  pedantic: ^1.8.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.4 <2.0.0"
